version: '2'

services:
    memcached:
        image: memcached:alpine
        container_name: Capella_Memcached
        ports:
            - 11211:11211
    php:
        build: php5.6-fpm
        container_name: Capella_PHP
        links:
            - memcached
        volumes:
            - ../capella:/var/www
    nginx:
        build: nginx
        container_name: Capella_NGINX
        ports:
            - 80:80
        links:
            - php
            - memcached
        volumes_from:
            - php
